services:
  laravel:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: weather-service-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - weather-service_net
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: weather-service-nginx
    restart: unless-stopped
    ports:
      - "8087:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - weather-service_net
    depends_on:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: weather-service-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - weather-service_net

networks:
  weather-service_net:
